spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/sports_platform
spring.datasource.username=postgres
spring.datasource.password=Lucamby0803
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

#API configuration
server.servlet.context-path=/api

# ==================== JWT Configuration ====================
jwt.secret=5ByA3k8mQpL9xWvNtRjUcZeYdFgHiOsSuTwXqKlMnBvC2D4E6G7H
jwt.expiration=86400000

# ==================== Flyway ====================
spring.flyway.enabled=false
